name: Build and Deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.API_URL }}
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Setup SSH
        run: |
          # создаем директорию для ключа
          mkdir -p ~/.ssh
          # выводим содержимое нашей переменной окружения в файл
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # ставим нужные безопасные права
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          # Добавляем отпечаток сервера
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          # воспользуемся SCP здесь, т.к. нам просто нужно загрузить из
          # одной директории
          ssh $SSH_USER@$SSH_HOST "mkdir -p ~/realworld/public"
          scp -r build/* $SSH_USER@$SSH_HOST:~/realworld/public
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
